all:
	make -C log
	make -C cdata_structures
	make -C centropy
	make -C packet
	make -C master_middlewares

fclean:
	make -C log fclean
	make -C packet fclean
	make -C master_middlewares fclean
	make -C centropy fclean
	make -C cdata_structures fclean
