#ifndef _REQUESTS_HANDLERS_H
# define _REQUESTS_HANDLERS_H

# define TYPE_T_REQUEST_INIT 0
# define TYPE_T_REQUEST_COMPUTATION 1
# define TYPE_T_REQUEST_TEXTURE 2
# define TYPE_T_REQUEST_SCENE 3
# define TYPE_T_REQUEST_FINISH 4

# define TYPE_T_RESPONSE_SUCCESS 0
# define TYPE_T_RESPONSE_UNRECOGNIZED 1
# define TYPE_T_RESPONSE_SYSTEM 2

#endif